language: java
git:
  depth: 3
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
    dist: trusty
  - os: linux
    jdk: oraclejdk11
    env: DEPLOY=true
  - os: osx 
    jdk: oraclejdk11
    env: DEPLOY=true
  - os: linux
    jdk: oraclejdk13

before_install: mkdir -p ~/.m2 && cp .settings.xml ~/.m2/settings.xml
install: mvn install -DskipTests=true
script: mvn test -Dassembly.skipAssembly=true -B
after_success:
  - test "$DEPLOY" = true -a "$TRAVIS_PULL_REQUEST" = false 
    && mvn source:jar deploy -DskipTests=true -B
